crossplane-contrib/provider-gcp

gcp/apis/cache/v1alpha2/doc.go
gcp/apis/cache/v1alpha2/register.go
gcp/apis/compute/v1alpha2/doc.go
gcp/apis/compute/v1alpha2/register.go
gcp/apis/database/v1alpha2/doc.go
gcp/apis/database/v1alpha2/register.go
gcp/apis/servicenetworking/v1alpha2/doc.go
gcp/apis/servicenetworking/v1alpha2/register.go
gcp/apis/storage/v1alpha2/doc.go
gcp/apis/storage/v1alpha2/register.go

Update GCP API package type documentation

---

Gopkg.lock

We want the fix from https://github.com/crossplaneio/crossplane-runtime/pull/18
I have:

Bump crossplane-runtime to fix predicates

---

Gopkg.lock
pkg/controller/gcp/cache/claim.go
pkg/controller/gcp/compute/claim.go
pkg/controller/gcp/database/claim.go
pkg/controller/gcp/storage/claim.go

claim predicates: remove hasdirectclassreferencekind in favor of ismanagedkind

---

Jenkinsfile
Makefile
cluster/local/helm-rbac.yaml
cluster/local/integration_tests.sh

Same as crossplaneio/stack-azure#29.
Fixes crossplaneio/crossplane#759
I have:

integration tests: initial implementation

---

Makefile

Do not use vendor make target as a dependency of reviewable target since we do not have vendor folder anymore and running it causes confusion for other tools when gomod is activated, for example GoLand.
I have:

Remove vendor make target as a dependency of reviewable

---

go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/database/claim.go
pkg/controller/storage/claim.go

See https://github.com/crossplaneio/crossplane-runtime/pull/55
I have:

Update crossplane-runtime to fix static provisioning

---

config/stack/manifests/resources/bucket.ui-schema.yaml
config/stack/manifests/resources/bucketclass.ui-schema.yaml
config/stack/manifests/resources/cloudmemorystoreinstance.ui-schema.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.ui-schema.yaml
config/stack/manifests/resources/cloudsqlinstance.ui-schema.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.ui-schema.yaml
config/stack/manifests/resources/connection.ui-schema.yaml
config/stack/manifests/resources/gkecluster.ui-schema.yaml
config/stack/manifests/resources/gkeclusterclass.ui-schema.yaml
config/stack/manifests/resources/globaladdress.ui-schema.yaml
config/stack/manifests/resources/network.ui-schema.yaml
config/stack/manifests/resources/provider.ui-schema.yaml
config/stack/manifests/resources/subnetwork.ui-schema.yaml

Per the [Stack UI Schema Status Spec](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#design), resources provided by a Stack may report to UI tools the status of the provisioned resource.
One approach to hint the UI, it a so-called [fallback option](https://github.com/crossplaneio/crossplane/blob/4cf353351fc7fa3d58210fc790a6b30e7f74309b/design/one-pager-stack-status-spec.md#fallback-option).  This approach defers to a "READY" additionalPrinterColumn defined in the CRD. Use of this approach would not require a `ui-schema.yaml` but resources in this Stack do not report the necessary READY column.
Because this Stack takes advantage of the Crossplane Runtime's Conditioned Status pattern, there is a predictable path …

stacks: report Ready status for all managed types using ui-schema

---

apis/compute/v1alpha2/gkecluster_types.go
apis/compute/v1alpha2/globaladdress_types.go
apis/compute/v1alpha2/subnetwork_types.go
apis/database/v1beta1/cloudsql_instance_types.go
apis/servicenetworking/v1alpha2/connection_types.go

https://github.com/golang/go/wiki/CodeReviewComments#error-strings
Updating these to match the Azure changes.
I have:

Avoid punctuation in error strings

---

pkg/controller/database/cloudsql.go
pkg/controller/database/cloudsql_test.go

Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>
Set conditions in Create and Delete for CloudSQL per our discussion [here](https://github.com/crossplaneio/stack-aws/pull/52#discussion_r339362138).
I have:

cloudsql: Set conditions in Create and Delete

---

apis/cache/v1beta1/cloudmemorystore_instance_types.go
apis/database/v1beta1/cloudsql_instance_types.go
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml

Some `v1beta1` printer fields no longer work. This updates them.
I have:

v1beta1: update printer fields to work with v1beta1 updates

---

pkg/clients/cloudsql/cloudsql.go
pkg/clients/cloudsql/cloudsql_test.go

cloudsql: fix thrashing on IsUpToDate by ignoring attr ref fields

---

apis/servicenetworking/v1alpha3/connection_types.go
apis/servicenetworking/v1alpha3/connection_types_test.go
go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/compute/claim.go
pkg/controller/database/claim.go
pkg/controller/storage/claim.go

https://github.com/crossplaneio/crossplane-runtime/releases/tag/v0.2.0
This update fixes several and requires a few API changes per the above release notes.
I have:

Update to crossplane-runtime v0.2.0

---

apis/servicenetworking/v1alpha3/connection_types.go
apis/servicenetworking/v1alpha3/connection_types_test.go
go.mod
go.sum
pkg/clients/cloudsql/cloudsql.go
pkg/clients/cloudsql/cloudsql_test.go
pkg/controller/cache/claim.go
pkg/controller/compute/claim.go
pkg/controller/database/claim.go
pkg/controller/storage/claim.go

Cherry picks commits from master fixing the following bugs in `stack-gcp`:
- https://github.com/crossplaneio/stack-gcp/issues/77
- Update `crossplane-runtime` to `v0.2.0`
Update to `v0.2.0` of `crossplane-runtime` includes the following fixes:
- https://github.com/crossplaneio/crossplane-runtime/issues/63
- https://github.com/crossplaneio/crossplane-runtime/issues/62
- https://github.com/crossplaneio/crossplane-runtime/issues/57
I have:

back-port fixes for v0.2.1

---

Makefile
apis/gcp.go
apis/generate.go
go.mod
go.sum

Note that this includes CRD generation, which has been subsumed by make generate in order to ensure we use the same controller-tools to generate Go code and CRDs.
I have:

Pin code generation tools using Go modules

---

go.mod
go.sum
pkg/clients/gke/gke.go
pkg/clients/gke/gke_test.go
pkg/controller/compute/gke.go
pkg/controller/compute/gke_test.go
pkg/controller/storage/bucket_operations.go
pkg/controller/storage/bucket_operations_test.go

Implements https://github.com/crossplaneio/crossplane/issues/861 for GKE.
I have:

gke: save raw kubeconfig to connection secret

---

cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml
config/stack/manifests/resources/bucketclass.resource.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gkeclusterclass.resource.yaml
config/stack/manifests/resources/provider.resource.yaml

Per https://github.com/crossplaneio/crossplane/blob/1fb67d0/docs/release/release-process.md#stack-release-process
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-azure/blob/master/config/stack/manifests/app.yaml

Prepare to release v0.3.0

---

config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstanceclasses.yaml
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/compute.gcp.crossplane.io_gkeclusterclasses.yaml
config/crd/compute.gcp.crossplane.io_gkeclusters.yaml
config/crd/compute.gcp.crossplane.io_globaladdresses.yaml
config/crd/compute.gcp.crossplane.io_networks.yaml
config/crd/compute.gcp.crossplane.io_subnetworks.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
config/crd/servicenetworking.gcp.crossplane.io_connections.yaml
config/crd/storage.gcp.crossplane.io_bucketclasses.yaml
config/crd/storage.gcp.crossplane.io_buckets.yaml
go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/compute/claim.go
pkg/controller/database/claim.go
pkg/controller/storage/bucket_operations.go
pkg/controller/storage/claim.go

Fixes #99 
This PR migrates stack-gcp to a build of crossplane-runtime that:
* Does not make resource claims the controller reference (or any kind of owner reference) of managed resources.
* Uses the managed resource's reclaim policy to determine whether it is deleted when its resource claim is deleted, with the exact same semantics as the upstream persistent volume reclaim policy.
I'm going to test this by dynamically provisioning a CloudSQLInstance, then restarting the Crossplane and Kubernetes control planes a bunch to ensure nothing is unexpectedly deleted.
I have:
[release notes]: …

Bump crossplane-runtime for updated ReclaimPolicy semantics

---

cluster/local/integration_tests.sh
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstanceclasses.yaml
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/compute.gcp.crossplane.io_gkeclusterclasses.yaml
config/crd/compute.gcp.crossplane.io_gkeclusters.yaml
config/crd/compute.gcp.crossplane.io_globaladdresses.yaml
config/crd/compute.gcp.crossplane.io_networks.yaml
config/crd/compute.gcp.crossplane.io_subnetworks.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
config/crd/servicenetworking.gcp.crossplane.io_connections.yaml
config/crd/storage.gcp.crossplane.io_bucketclasses.yaml
config/crd/storage.gcp.crossplane.io_buckets.yaml
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml
go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/compute/claim.go
pkg/controller/database/claim.go
pkg/controller/storage/bucket_operations.go
pkg/controller/storage/claim.go

Prep release 0.3.1

---

examples/cache/rediscluster/resource-claim.yaml
examples/cache/rediscluster/resource-class.yaml
examples/compute/kubernetescluster/resource-claim.yaml
examples/compute/kubernetescluster/resource-class.yaml
examples/database/mysqlinstance/resource-claim.yaml
examples/database/mysqlinstance/resource-class.yaml
examples/database/postgresqlinstance/resource-claim.yaml
examples/database/postgresqlinstance/resource-class.yaml
examples/gcp-credentials.sh
examples/gcp-provider.yaml
examples/stack-gcp.yaml
examples/storage/bucket/resource-claim.yaml
examples/storage/bucket/resource-class.yaml

Copies GCP examples from core crossplane repository. After all examples are moved to individual stacks we can begin removing from core crossplane and only keeping full length examples (such as wordpress deployment) in the repo.
I have:

examples: move examples from crossplane repo

---

apis/cache/v1beta1/cloudmemorystore_instance_types.go
apis/compute/v1alpha3/gkecluster_types.go
apis/compute/v1alpha3/globaladdress_types.go
apis/compute/v1alpha3/network_types.go
apis/compute/v1alpha3/subnetwork_types.go
apis/database/v1beta1/cloudsql_instance_types.go
apis/servicenetworking/v1alpha3/connection_types.go
apis/storage/v1alpha3/types.go
apis/v1alpha3/types.go
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstanceclasses.yaml
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/compute.gcp.crossplane.io_gkeclusters.yaml
config/crd/compute.gcp.crossplane.io_globaladdresses.yaml
config/crd/compute.gcp.crossplane.io_networks.yaml
config/crd/compute.gcp.crossplane.io_subnetworks.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
config/crd/gcp.crossplane.io_providers.yaml
config/crd/servicenetworking.gcp.crossplane.io_connections.yaml
config/crd/storage.gcp.crossplane.io_buckets.yaml

Validates the `spec` and `forProvider` are present on all managed resources so that we don't hit nil pointer exceptions in controllers.
I have:

api: require spec and forProvider in all resources

---

pkg/controller/container/nodepool.go
pkg/controller/container/nodepool_test.go

Fixes conflict introduced by merge of #114 after #115
I have:

Fix merge conflicts from update provider secret refs

---

go.mod
go.sum

(cherry picked from commit 8e6c26e8e3a6254d0caf0f2e61efff90049c4879)
Backports work from #127 
I have:

[Backport to Release v0.4] crossplane: pin to v0.6

---

cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml

Bumps `stack-gcp` version refs to `v0.4.1` in preparation for patch release.
I have:

Bump stack-gcp version refs to v0.4.1

---

config/stack/manifests/resources/bucket.ui-schema.yaml
config/stack/manifests/resources/bucketclass.ui-schema.yaml
config/stack/manifests/resources/cloudmemorystoreinstance.ui-schema.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.ui-schema.yaml
config/stack/manifests/resources/cloudsqlinstance.ui-schema.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.ui-schema.yaml
config/stack/manifests/resources/connection.ui-schema.yaml
config/stack/manifests/resources/gkecluster.ui-schema.yaml
config/stack/manifests/resources/gkeclusterclass.ui-schema.yaml
config/stack/manifests/resources/globaladdress.ui-schema.yaml
config/stack/manifests/resources/network.ui-schema.yaml
config/stack/manifests/resources/provider.ui-schema.yaml
config/stack/manifests/resources/subnetwork.ui-schema.yaml

Per https://github.com/crossplaneio/crossplane/pull/1145
Signed-off-by: Steven Rathbauer <steven@rathpc.com>

Update resourceConditionPaths --> new printerColumns syntax

---

Jenkinsfile.integration
Makefile
test/integration/gkecluster_dynamic_test.go
test/integration/gkecluster_static_test.go
test/integration/util.go
test/testdata/gkecluster_dynamic/gkeclusterclass.yaml
test/testdata/gkecluster_dynamic/kubernetesclusterclaim.yaml
test/testdata/gkecluster_dynamic/provider.yaml
test/testdata/gkecluster_static/gkecluster.yaml
test/testdata/gkecluster_static/provider.yaml

Adds additional integration tests including static and dynamic provisioning of GKE clusters.
I have:

integration: add e2e tests

---

cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml
config/stack/manifests/resources/bucketclass.resource.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gkeclusterclass.resource.yaml
config/stack/manifests/resources/provider.resource.yaml
examples/stack-gcp.yaml

Bumps references to stack-gcp v0.5.0 and Crossplane 0.7
I have:

v0.5.0: docs and references prep

---

cmd/stack/main.go
go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/cache/managed.go
pkg/controller/compute/claim.go
pkg/controller/compute/gke.go
pkg/controller/compute/gke_test.go
pkg/controller/compute/globaladdress.go
pkg/controller/compute/network.go
pkg/controller/compute/subnetwork.go
pkg/controller/compute/target.go
pkg/controller/container/claim.go
pkg/controller/container/cluster.go
pkg/controller/container/nodepool.go
pkg/controller/container/target.go
pkg/controller/database/claim.go
pkg/controller/database/cloudsql.go
pkg/controller/gcp.go
pkg/controller/servicenetworking/connection.go
pkg/controller/storage/bucket.go
pkg/controller/storage/bucket_test.go
pkg/controller/storage/claim.go

crossplaneio/crossplane-runtime#108
This commit updates all stack-gcp controllers to use the logging and event recording functionality added in the above crossplane-runtime PR. Legacy controllers are minimally updated to avoid package scoped loggers.
I have:

Plumb up logging and event recorder implementations

---

apis/storage/v1alpha3/types.go

https://github.com/crossplaneio/crossplane-runtime/issues/1
This function and the util package it lives in are deprecated. They'll be replaced by the new crossplane.io/external-name annotation once we port this controller to the managed resource reconciler. For now I'd like to remove it from crossplane-runtime/pkg/util as it is only used by the bucket controllers.
I have:
[stack resources documentation]: …

Rehome deprecated ConditionalStringFormat from crossplane-runtime

---

apis/database/v1beta1/cloudsql_instance_types.go
go.mod
go.sum
pkg/controller/database/cloudsql.go
pkg/controller/database/cloudsql_test.go

The former has been replaced by the latter. This also removes part of a test that was never invoked.
I have:

Switch util.GeneratePassword to password.Generate

---

test/integration/create_classes_test.go
test/integration/gkecluster_dynamic_test.go
test/integration/gkecluster_static_test.go

Updates the integration tests to use the new controller setup function that was changed during the logging and eventing work. This is currently causing integration tests to fail.
I have:

Update integration tests to use new controller setup func

---

go.mod
go.sum
pkg/clients/cloudmemorystore/cloudmemorystore.go
pkg/clients/cloudmemorystore/cloudmemorystore_test.go
pkg/clients/cloudsql/cloudsql.go
pkg/clients/cloudsql/cloudsql_test.go
pkg/clients/cluster/cluster.go
pkg/clients/cluster/cluster_test.go
pkg/clients/nodepool/nodepool.go
pkg/clients/nodepool/nodepool_test.go
pkg/controller/cache/managed.go
pkg/controller/container/cluster.go
pkg/controller/container/cluster_test.go
pkg/controller/container/nodepool.go
pkg/controller/container/nodepool_test.go
pkg/controller/database/cloudsql.go
pkg/controller/database/cloudsql_test.go

First pass at fix for issue described in #164. Only `CloudSQL` has been updated, but I want to get consensus on how we want to address this issue (either using what is proposed here or not) before fixing other `IsUpToDate` functions as well.
Fix #164 
I have:

Fix up to date check logic

---

apis/cache/v1beta1/register.go
apis/compute/v1alpha3/register.go
apis/container/v1alpha1/register.go
apis/container/v1beta1/register.go
apis/database/v1beta1/register.go
apis/servicenetworking/v1beta1/register.go
apis/storage/v1alpha3/register.go
apis/v1alpha3/register.go
go.mod
go.sum
pkg/controller/cache/claim.go
pkg/controller/cache/managed.go
pkg/controller/compute/claim.go
pkg/controller/compute/gke.go
pkg/controller/compute/globaladdress.go
pkg/controller/compute/network.go
pkg/controller/compute/subnetwork.go
pkg/controller/compute/target.go
pkg/controller/container/claim.go
pkg/controller/container/cluster.go
pkg/controller/container/nodepool.go
pkg/controller/container/target.go
pkg/controller/database/claim.go
pkg/controller/database/cloudsql.go
pkg/controller/servicenetworking/connection.go
pkg/controller/storage/bucket.go
pkg/controller/storage/claim.go

Per https://github.com/crossplaneio/crossplane/issues/1254
I have:

Use GroupKind, not Kind, for controller names

---

cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/install.yaml
config/stack/manifests/resources/bucketclass.resource.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gkeclusterclass.resource.yaml
config/stack/manifests/resources/provider.resource.yaml
examples/stack-gcp.yaml

Prep docs and references for `v0.6.0` release.
I have:

[v0.6.0]: prep docs and references

---

README.md
config/stack/manifests/resources/bucketclass.resource.yaml
config/stack/manifests/resources/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gkeclusterclass.resource.yaml
config/stack/manifests/resources/provider.resource.yaml

A few follow-up updates after rename to `crossplaneio`.
I have:
[`app.yaml`]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/app.yaml
[stack resources documentation]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/resources

Update resource manifests to new api docs link

---

README.md
cluster/local/integration_tests.sh
config/stack/manifests/app.yaml
config/stack/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/stack/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml
config/stack/samples/install.stack.yaml
examples/stack-gcp.yaml

Prep docs and references for v0.7.0 release
I have:

[release-0.7] Prep docs and references for v0.7.0 release

---

README.md
config/stack/manifests/app.yaml
config/stack/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/stack/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml

The `portable resource abstractions` link no longer exists (this change was already made in release). The docs api references no longer exist on `master` and the `v0.7` release was the last one in which they did. These changes also remove almost all updates required in our branch prep PRs. I will update other provider repos as well if this one is merged.
I have:
[stack resources …

Remove missing docs links and minimize release branch prep

---

go.mod
go.sum
pkg/controller/container/secret.go
pkg/controller/gcp.go

Adds continuous secret propagation controller for `v1beta1` `GKECluster`
*Note: DO NOT MERGE until I complete manual testing.*
I have:

Continuously propagate v1beta1 GKECluster connection secrets

---

apis/compute/v1beta1/globaladdress_referencers_test.go
go.mod
go.sum
pkg/clients/cloudmemorystore/cloudmemorystore_test.go
pkg/controller/cache/managed_test.go
pkg/controller/compute/globaladdress_test.go
pkg/controller/compute/network_test.go
pkg/controller/compute/subnetwork_test.go
pkg/controller/container/cluster_test.go
pkg/controller/container/nodepool_test.go
pkg/controller/database/cloudsql_test.go

This brings in updated claim binding, managed resource, and secret propagation controllers that support backing up and restoring Crossplane resources.
I have:

Bump crossplane-runtime dependency

---

go.mod
go.sum

Does as title suggests.
I have:

Bump crossplane dependency to latest master

---

cluster/local/integration_tests.sh
config/stack/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/stack/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml
config/stack/samples/install.stack.yaml
examples/stack-gcp.yaml

Prep docs and references for v0.8.0 release.
*Note: docs links will be picked up and generated automatically after tag*
I have:

[release-0.8] Prep docs and references for v0.8.0 release

---

apis/cache/v1beta1/cloudmemorystore_instance_types.go
apis/compute/v1alpha3/gkecluster_types.go
apis/compute/v1beta1/globaladdress_types.go
apis/compute/v1beta1/network_types.go
apis/compute/v1beta1/subnetwork_types.go
apis/container/v1alpha1/nodepool_types.go
apis/container/v1beta1/gkecluster_types.go
apis/database/v1beta1/cloudsql_instance_types.go
apis/servicenetworking/v1beta1/connection_types.go
apis/storage/v1alpha3/types.go
apis/v1alpha3/types.go
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstanceclasses.yaml
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/compute.gcp.crossplane.io_gkeclusterclasses.yaml
config/crd/compute.gcp.crossplane.io_gkeclusters.yaml
config/crd/compute.gcp.crossplane.io_globaladdresses.yaml
config/crd/compute.gcp.crossplane.io_networks.yaml
config/crd/compute.gcp.crossplane.io_subnetworks.yaml
config/crd/container.gcp.crossplane.io_gkeclusterclasses.yaml
config/crd/container.gcp.crossplane.io_gkeclusters.yaml
config/crd/container.gcp.crossplane.io_nodepoolclasses.yaml
config/crd/container.gcp.crossplane.io_nodepools.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
config/crd/gcp.crossplane.io_providers.yaml
config/crd/servicenetworking.gcp.crossplane.io_connections.yaml
config/crd/storage.gcp.crossplane.io_bucketclasses.yaml
config/crd/storage.gcp.crossplane.io_buckets.yaml

These categories allow for instances of provider-gcp CRDs to be group listed. The added categories are as follows:
* Manged Resources: crossplane, managed, gcp
* Classes: crossplane, class, gcp
* Provider: crossplane, provider, gcp
I will apply to other providers as well if approved here.
I have:
[stack resources documentation]: https://github.com/crossplane/provider-gcp/blob/master/config/ …

Add categories to all CRDs

---

cluster/images/provider-gcp/Dockerfile

This updates the provider-gcp Dockerfile to run as non-root as the Crossplane stack manager will refuse to run containers as root by default per https://github.com/crossplane/crossplane/pull/1444.
Tested by running the Crossplane stack manager against a KIND cluster on my fork of the PR above, then building this fork of `provider-gcp`, loading it into KIND and creating a `ClusterStackInstall`. The provider was deployed successfully. I then double checked by installing the current `master` version of `provider-gcp` and confirmed that it received a `CreateContainerConfigError` because it was attempting to run as root.
I have:
[examples]: …

Run provider-gcp controllers as non-root

---

cluster/local/integration_tests.sh
config/stack/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/stack/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/stack/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/stack/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/stack/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml
config/stack/samples/install.stack.yaml
examples/stack-gcp.yaml

Prep docs and references for v0.9.0 release
I have:

[release-0.9] Prep docs and references for v0.9.0 release

---

apis/cache/v1beta1/cloudmemorystore_instance_types.go
apis/compute/v1alpha3/gkecluster_types.go
apis/compute/v1beta1/globaladdress_types.go
apis/compute/v1beta1/network_types.go
apis/compute/v1beta1/subnetwork_types.go
apis/container/v1alpha1/nodepool_types.go
apis/container/v1beta1/gkecluster_types.go
apis/database/v1beta1/cloudsql_instance_types.go
apis/iam/v1alpha1/serviceaccount_types.go
apis/servicenetworking/v1beta1/connection_types.go
apis/storage/v1alpha3/types.go
config/crd/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
config/crd/compute.gcp.crossplane.io_gkeclusters.yaml
config/crd/compute.gcp.crossplane.io_globaladdresses.yaml
config/crd/compute.gcp.crossplane.io_networks.yaml
config/crd/compute.gcp.crossplane.io_subnetworks.yaml
config/crd/container.gcp.crossplane.io_gkeclusters.yaml
config/crd/container.gcp.crossplane.io_nodepools.yaml
config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
config/crd/iam.gcp.crossplane.io_serviceaccounts.yaml
config/crd/servicenetworking.gcp.crossplane.io_connections.yaml
config/crd/storage.gcp.crossplane.io_buckets.yaml

Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>
Some of the resources do not have them.
I have:

Add Ready and Synced printer columns to all resources

---

go.mod
go.sum

Pin dependencies ahead of branch cut.
I have:

Pin crossplane and crossplane-runtime ahead of release-0.10 branch cut

---

cluster/local/integration_tests.sh
config/package/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/package/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/package/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/package/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/package/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/package/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml
config/package/samples/install.package.yaml
examples/provider-gcp.yaml

Prep docs and references for `v0.10.0` release.
I have:

[release-0.10] Prep docs and references for v0.10.0 release

---

Makefile

Add ability to quickly start provider-gcp controllers running against a kind cluster.
Depends on https://github.com/crossplane/crossplane/pull/1594
I have:

Add local kind dev commands to Makefile

---

cluster/local/integration_tests.sh
config/package/manifests/resources/cache.gcp.crossplane.io/cloudmemorystoreinstanceclass.resource.yaml
config/package/manifests/resources/compute.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/package/manifests/resources/container.gcp.crossplane.io/gkeclusterclass.resource.yaml
config/package/manifests/resources/database.gcp.crossplane.io/cloudsqlinstanceclass.resource.yaml
config/package/manifests/resources/gcp.crossplane.io/provider.resource.yaml
config/package/manifests/resources/storage.gcp.crossplane.io/bucketclass.resource.yaml
config/package/samples/install.package.yaml
examples/provider-gcp.yaml

Prep docs and references for v0.11.0 release
I have:

[release-0.11] Prep docs and references for v0.11.0 release

---

go.mod
go.sum
pkg/controller/database/cloudsql.go
pkg/controller/iam/managed.go
pkg/controller/pubsub/topic.go

Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>
See https://github.com/crossplane/crossplane/issues/1686 for more context.
I have:

update initializers to include providerconfig defaulter

---

Makefile

The current implementation does not work on OS X due to differences in how sed works.
I have:

Make crds.clean rule portable

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/golangci-lint.yml
Makefile
apis/container/v1alpha1/nodepool_types.go
apis/container/v1beta1/gkecluster_types.go
apis/iam/v1alpha1/serviceaccount_types.go
pkg/clients/nodepool/nodepool.go

Updates PR and issue templates as well as GitHub workflows and build submodule to match crossplane/crossplane#1775.
I have:

Match crossplane/crossplane build and GitHub configuration

---

apis/compute/v1beta1/referencers.go
apis/container/v1alpha1/referencers.go
apis/container/v1beta1/referencers.go
apis/database/v1beta1/referencers.go
apis/servicenetworking/v1beta1/referencers.go

See https://github.com/crossplane/crossplane/issues/1499
I have:

Wrap ref resolution errors with context

---

cluster/images/provider-gcp/Dockerfile
cluster/images/provider-gcp/Makefile
cluster/local/integration_tests.sh

Updates the provider package image to only include a single static
package.yaml file that can be parsed by the package manager.
Signed-off-by: hasheddan georgedanielmangum@gmail.com
I have:
See crossplane/provider-aws#365 and crossplane/crossplane#1756 for more info.

Build provider packages with static content 

---

apis/v1beta1/zz_generated.pc.go
go.mod
go.sum
package/crds/gcp.crossplane.io_providerconfigs.yaml
pkg/clients/gcp.go

See https://github.com/crossplane/crossplane-runtime/pull/212 for context. 
I have:
I've run through `example/in-composition` from https://github.com/crossplane-contrib/provider-helm (which uses this provider).

Use distinct ProviderConfig credentials field

---

pkg/clients/nodepool/nodepool.go
pkg/clients/nodepool/nodepool_test.go

Signed-off-by: Hasan Turken <turkenh@gmail.com>
Fixes #288
I have:
Added relevant unit tests

Fix nodepool auto upgrade issue

---

go.mod
go.sum

Updates crossplane-runtime dependency to v0.13.0.
I have:
`make build`

Pin crossplane-runtime to v0.13.0

---

Makefile

Fixes `make dev` target
I have:
verified that `make dev` is now working
also `make generate` isn't changed

use CRD_DIR variable

---

apis/storage/v1alpha3/types.go
package/crds/storage.gcp.crossplane.io_buckets.yaml

Fix notFoundPage typo

---

pkg/clients/topic/topic_test.go
pkg/controller/pubsub/topic_test.go

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>
nit : Function names in tests were mismatched
Fixes #
I have:

Fix naming test cases

---

package/crossplane.yaml

Per crossplane/crossplane#2299
Fixes #
I have:
I'm confident enough from testing a similar change at https://github.com/crossplane/provider-azure/pull/244.

Use recommended packaging format

---

package/crossplane.yaml

Per crossplane/crossplane#2299 , we'd like to have a patch release of providers to expose that metadata.
I have:
N/A

Backport new package metadata format to 0.17

---

go.mod
go.sum
package/crds/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml
package/crds/compute.gcp.crossplane.io_globaladdresses.yaml
package/crds/compute.gcp.crossplane.io_networks.yaml
package/crds/compute.gcp.crossplane.io_subnetworks.yaml
package/crds/container.gcp.crossplane.io_clusters.yaml
package/crds/container.gcp.crossplane.io_nodepools.yaml
package/crds/database.gcp.crossplane.io_cloudsqlinstances.yaml
package/crds/iam.gcp.crossplane.io_serviceaccountkeys.yaml
package/crds/iam.gcp.crossplane.io_serviceaccountpolicies.yaml
package/crds/iam.gcp.crossplane.io_serviceaccounts.yaml
package/crds/kms.gcp.crossplane.io_cryptokeypolicies.yaml
package/crds/kms.gcp.crossplane.io_cryptokeys.yaml
package/crds/kms.gcp.crossplane.io_keyrings.yaml
package/crds/pubsub.gcp.crossplane.io_topics.yaml
package/crds/servicenetworking.gcp.crossplane.io_connections.yaml
package/crds/storage.gcp.crossplane.io_bucketpolicies.yaml
package/crds/storage.gcp.crossplane.io_bucketpolicymembers.yaml
package/crds/storage.gcp.crossplane.io_buckets.yaml

Use latest to get the new CRD changes such as defaults.
Fixes #
I have:
`make reviewable`

Bump crossplane-runtime version

---

apis/storage/v1alpha1/bucketpolicy_types.go
apis/storage/v1alpha1/bucketpolicymember_types.go
package/crds/storage.gcp.crossplane.io_bucketpolicies.yaml
package/crds/storage.gcp.crossplane.io_bucketpolicymembers.yaml
pkg/clients/bucketpolicy/bucketpolicy.go

These are not KMS Cloud Keys at all.
I have:
Just `make reviewable`, which seems like enough for this change.

Fix some copy pasta in bucket policy controllers

---

package/crds/database.gcp.crossplane.io_cloudsqlinstances.yaml

- Runned `make generate` to fix missing YAML manifests that were causing the failure of the `check-diff` CI job.
I have:
N/A

Fix failing check-diff job at master branch

---

OWNERS.md

Proposing Gabriel Ferreira (@Feggah) as a maintainer.
@Feggah is pretty active in this repository and is interested in being a maintainer. 
Thanks a lot for all your contributions!
I have:
N/A

Add Gabriel Ferreira as a maintainer

---

apis/cache/v1beta1/cloudmemorystore_instance_types.go
package/crds/cache.gcp.crossplane.io_cloudmemorystoreinstances.yaml

Fixes #425
I have:
- Creating a Memorystore with version 6.x

Add documentation about new supported Redis versions

---

.github/workflows/ci.yml
.github/workflows/promote.yml
Makefile
package/crossplane.yaml

Updates the package crossplane.yaml to reference source code in the
crossplane-contrib GitHub org.
Updates the Makefile to push to crossplane-contrib on Upbound and
crossplanecontrib on DockerHub.
Updates the GitHub workflows to use the appropriate user for pushing to
crossplanecontrib.
I have:
Verified updates worked correctly in `provider-aws`.

Update pushing to crossplane-contrib

---

.github/workflows/promote.yml

- Pin Go version in the Promote workflow to fix [this error](https://github.com/crossplane-contrib/provider-gcp/actions/runs/3222764556)
I have:
N/A

Pin go version in the promote workflow
