crossplane-contrib/provider-gcp

Gopkg.lock, gcp/apis/cache/v1alpha2/cloudmemorystore_instance_types_test.go, gcp/apis/compute/v1alpha2/types_test.go, gcp/apis/database/v1alpha2/cloudsql_instance_types_test.go, gcp/apis/storage/v1alpha2/types_test.go, gcp/apis/v1alpha2/types_test.go, pkg/test/crds.go
This was missed in the original porting from the main crossplane repo.  The API unit tests need to know where to find the CRDs at test runtime.  Each repo should have its own implementation of that, specific to the location of CRDs for the local repo.
I have:
=> test: implement test CRDs() function specific to this stack-gcp repo

Jenkinsfile, pkg/controller/gcp/compute/network.go
This PR is attempting to get official builds running on Jenkins in a new stack-gcp pipeline: https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fstack-gcp/activity
We'll want to have the same full functionality that the main crossplane repo has, such as SonarCloud checks and Integration tests, but I'm stripping the Jenkinsfile down for now just to get the build pipeline off the ground.
=> Get official builds running for stack-gcp repo

pkg/controller/gcp/compute/subnetwork.go
Do not include network name in subnetwork body that is used in Update calls.
Fixes #8 
I have:
=> Network name in Update call of Subnetwork Controller

Makefile
Signed-off-by: soorena776 <javad@upbound.io>
I have:
=> Move manifests target to `kubebuilder.mk` in build submodule

pkg/clients/cloudsql/cloudsql.go, pkg/clients/cloudsql/cloudsql_test.go
Fixes the `ipv4Enabled` field's issue. During the refactoring, I must've omitted it somehow. Detailed information here https://github.com/crossplaneio/stack-gcp/issues/15
I have:
=> cloudsql: ipv4Enabled should be force-sent 

pkg/controller/database/cloudsql.go, pkg/controller/database/cloudsql_test.go
We decided for v1beta1 resources that we would return an error when trying to create an external resource that already exists, because otherwise we risk accidentally 'adopting' existing managed resources into Crossplane management.
I believe all other v1beta1 resources follow this pattern, but CloudSQL was silently proceeding when it could not create an instance because the instance already existed.
I have:
=> Surface errors when a CloudSQL instance already exists

pkg/controller/cache/managed.go, pkg/controller/cache/managed_test.go
Propagate port to connection secret using new port constant from crossplane-runtime.
I have:
=> cloudmemorystore: propagate port to connection secret

pkg/clients/cloudsql/cloudsql.go, pkg/controller/database/cloudsql.go
Up-to-date check implementation was buggy. It compared _current params + late-init_ with current state. But it should actually compare _empty params + late-init_ with the current state. It always returned `true` until this PR.
I have:
=> cloudsql: fix up-to-date check bug

config/stack/manifests/app.yaml, config/stack/manifests/install.yaml
This PR bumps the stack version to v0.2.0 in its internal metadata.
I have:
[`app.yaml`]: https://github.com/crossplaneio/stack-aws/blob/master/config/stack/manifests/app.yaml
[skip ci]
=> build: bump stack version to v0.2.0

pkg/controller/database/cloudsql.go, pkg/controller/database/cloudsql_test.go
Fixes #100
When trying to create a SQL Instance with a name that is already
in use, we returned a more or less generic "create failed" error
message and the return code 409. As 409 indicates that the name
of the SQL instance is in use or has been in use recently, this
commit improves the message that is returned to the user.
I have:
-> `make: *** No rule to make target "generate", needed by "reviewable".  Stop.`
Local `go test` is running through fine though 🙂
=> improve error message when instance name is in use

cluster/local/integration_tests.sh, config/stack/manifests/app.yaml, config/stack/manifests/install.yaml, config/stack/manifests/resources/bucketclass.resource.yaml, config/stack/manifests/resources/cloudmemorystoreinstanceclass.resource.yaml, config/stack/manifests/resources/cloudsqlinstanceclass.resource.yaml, config/stack/manifests/resources/gkeclusterclass.resource.yaml, config/stack/manifests/resources/provider.resource.yaml
This PR bumps the internal stack references to the soon to be released version of v0.4.0, as well as updating the stack resource readmes to reference the soon to be released crossplane.io docs version 0.6.
I have:
=> Bump stack-gcp version refs to v0.4.0

apis/storage/v1alpha3/types.go, config/crd/storage.gcp.crossplane.io_bucketclasses.yaml, config/crd/storage.gcp.crossplane.io_buckets.yaml
Adds missing documentation for `ACLRule` of GCP buckets.
I have:
=> bucket: add documentation and validation for bucket ACL rule

pkg/clients/cloudsql/cloudsql.go, pkg/clients/cloudsql/cloudsql_test.go, pkg/clients/cluster/cluster.go, pkg/clients/cluster/cluster_test.go, pkg/controller/database/cloudsql.go, pkg/controller/database/cloudsql_test.go
Skip update if the creation is still ongoing. Also fixes:
- Values of `ForceSendFields` as they have to match _exact_ Go struct field names that you'd like to force send.
- `LateInitializeBool` should not return `nil` in case the incoming value is `false`, it causes unnecessary updates. In fact, incoming value shouldn't be considered in the decision of whether the value should be assigned.
Fixes #121 
I have:
=> CloudSQL controller should skip update during creation

test/integration/gkecluster_dynamic_test.go, test/integration/gkecluster_static_test.go, test/integration/util.go
@suskin caught some issues in the `waitFor` function that was being used in integration tests to observe created resources in the cluster. This PR fixes the both the leaking of goroutines and also implements the wait interval as expected.
I have:
=> integration tests: fix leaked goroutines

pkg/controller/cache/claim.go, pkg/controller/compute/claim.go
Claim controllers should use their claim kind, not managed resource kind, as their controller name. Typically there will be one one controller for each kind of resource claim per infrastructure stack.
I have:
=> Fix resource claim kinds in controller names

apis/database/v1beta1/cloudsql_instance_types.go, pkg/controller/database/cloudsql.go, pkg/controller/database/cloudsql_test.go
Expose connectionName in the connection secret to enable CloudSQL proxy connections.
I have:
=> Expose connectionName of CloudSQLInstance in connection secret

apis/container/v1beta1/gkecluster_types.go, apis/database/v1beta1/cloudsql_instance_types.go, config/crd/container.gcp.crossplane.io_gkeclusterclasses.yaml, config/crd/container.gcp.crossplane.io_gkeclusters.yaml, config/crd/database.gcp.crossplane.io_cloudsqlinstanceclasses.yaml, config/crd/database.gcp.crossplane.io_cloudsqlinstances.yaml
Parameters structs should be the first struct in API types so that they appear on top in docs. Otherwise it's really hard to browse the API reference doc and find how you should construct your object.
I have:
=> Parameter structs should appear on top in API reference docs

pkg/controller/cache/managed.go, pkg/controller/database/cloudsql.go
When `Update` is called on a resource, the resulting object deep copied into what's sent, meaning `status` sub resource gets deleted. This shows itself in occasions where the controller constantly late-inits, which is rare, but when it does the status is emptied.
I have:
=> Cloudsql and Cloudmemoryinstance status update fix

pkg/controller/servicenetworking/connection.go, pkg/controller/servicenetworking/connection_test.go
Do a forced update instead of create to work around the GCP connection creation bug. Tested it manually.
Fixes https://github.com/crossplaneio/stack-gcp/issues/80
I have:
=> Fix connection creation bug

pkg/clients/cloudsql/cloudsql.go, pkg/clients/cloudsql/cloudsql_test.go, pkg/clients/cluster/cluster.go, pkg/clients/nodepool/nodepool.go
Follow up on #166 that causes our comparison functions to treat all maps and slices with a length of zero to be equal, regardless of whether they are nil. I ran into a constantly updating instance that was being triggered by this check. I don't think it should cause any problems with needing an update when a slice or map has changed (i.e. if it either was of length zero or will be of length zero then it by definition had to change its length, meaning this check will produce a diff).
I have:
[release notes]: https://github.com/crossplaneio/crossplane/tree/master/PendingReleaseN …
=> Do not issue update when diff is nil vs empty for either slices or maps

go.mod, go.sum
Pins Crossplane and crossplane-runtime dependencies.
I have:
=> Pin crossplane to v0.8.0 and crossplane-runtime to v0.5.0

pkg/clients/nodepool/nodepool.go, pkg/clients/nodepool/nodepool_test.go
Modifies `UpToDate` logic for `NodePool` to ignore `Labels` and `Taints` with key `sandbox.gke.io/runtime`, which GCP adds automatically when certain sandbox configuration is provided (i.e. `gVisor`).
Ref: https://github.com/crossplane/crossplane-runtime/issues/120
Additional context on why a user can't manually provide these fields:
```
- lastTransitionTime: "2020-02-21T21:39:45Z" 
message: 'create failed: cannot create GKE node pool: googleapi: Error 400:
Node label "sandbox.gke.io/runtime" is reserved for gke sandbox., badRequest'
reason: Encountered an error during resource reconciliation
status: "False"
type: Synced
```
I have:
[examples]: …
=> Ignore gke added labels and taints on node pools

apis/container/v1alpha1/nodepool_types.go, apis/container/v1beta1/gkecluster_types.go, examples/container/kubernetescluster/resource-claim.yaml
Fixes `acceleratorCount` field of NodePools. The marshalling gets crazy when you got `,string"` for a non-string type.
I have:
[`app.yaml`]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/app.yaml
[stack resources documentation]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/resources
=> Remove string marshalling tag to fix nodepool accelerators field

apis/cache/v1beta1/zz_generated.managed.go, apis/compute/v1alpha3/zz_generated.managed.go, apis/compute/v1beta1/zz_generated.managed.go, apis/container/v1alpha1/zz_generated.managed.go, apis/container/v1beta1/zz_generated.managed.go, apis/database/v1beta1/zz_generated.managed.go, apis/servicenetworking/v1beta1/zz_generated.managed.go, apis/storage/v1alpha3/zz_generated.managed.go, go.mod, go.sum, pkg/controller/database/cloudsql.go
An example implementation of external tagging. This PR depends on https://github.com/crossplane/crossplane-runtime/pull/123 and https://github.com/crossplane/crossplane-tools/pull/17
Fixes #184 
I have:
[`app.yaml`]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/app.yaml
[stack resources documentation]: https://github.com/crossplane/stack-gcp/blob/master/config/stack/manifests/resources
=> cloudsql: implement external tagging

apis/storage/v1alpha3/types.go, apis/storage/v1alpha3/types_test.go, config/crd/storage.gcp.crossplane.io_bucketclasses.yaml, config/crd/storage.gcp.crossplane.io_buckets.yaml, examples/storage/bucket/resource-claim.yaml, pkg/controller/storage/bucket.go, pkg/controller/storage/bucket_operations.go, pkg/controller/storage/bucket_operations_test.go, pkg/controller/storage/bucket_test.go, pkg/controller/storage/claim.go, pkg/controller/storage/claim_test.go
Use external name annotation for bucket name as part of backup compatibility effort in https://github.com/crossplane/provider-gcp/issues/207
Manually tested.
I have:
=> bucket: use external name annotation for naming the bucket

pkg/clients/cluster/cluster.go, pkg/clients/cluster/cluster_test.go
We set ForceSendFields when we want to issue an update that includes a zero-value. However, when comparing to check if an object is up to date with its external representation, we do not want to check the ForceSendFields field in the diff.
Note: this bug does not actually degrade performance of GKE clusters, it just hits the GCP API with a bunch of no-op updates.
I tested with the following class and claim to make sure that resources reached a stable state and did not continually issue updates:
```
apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKEClusterClass
metadata:
labels:
cool: label
name: cool-cluster
specTemplate:
forProvider:
description: A cool cluster
addonsConfig:
cloudRunConfig:
disabled: false …
```
=> Ignore ForceSendFields when checking IsUpToDate

apis/container/v1alpha1/nodepool_types.go, config/crd/container.gcp.crossplane.io_nodepools.yaml
While testing, I realized the raw cluster name is too long for a printer column and it messes up the layout. I believe in most of the cases, the cluster is referenced, so, using the name of `container.GKECluster` CR that is referenced could be nicer.
I have:
=> Raw cluster name in spec is too long for printer column

Makefile
The crds.clean syntax seems to work correctly but emits a warning that
it cannot read the file when running on linux. This updates to a replace
format that is compatible with both linux and darwin systems.
See `check-diff` logs [here](https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fprovider-gcp-pipelines%2Fprovider-gcp/detail/master/151/pipeline/29) for example.
Follow-up to #258 
I have:
Ran `make generate` on both mac and ubuntu system.
=> Clean up crds.clean output on linux

apis/container/v1alpha1/nodepool_types.go, apis/container/v1beta1/gkecluster_types.go, apis/storage/v1alpha3/types.go, package/crds/container.gcp.crossplane.io_gkeclusters.yaml, package/crds/container.gcp.crossplane.io_nodepools.yaml, package/crds/storage.gcp.crossplane.io_buckets.yaml
Reclaim policy and resource classes have been removed so printer columns
for them will never be populated. This removes any printer columns that
use these fields.
xref https://github.com/crossplane/crossplane/issues/1781
I have:
`make generate`
=> Remove printer columns for unused fields

package/crossplane.yaml
Adding basic metadata to `crossplane.yaml` to improve package discovery/browsing in a registry.
=> Adding metadata to crossplane.yaml

pkg/controller/storage/managed.go
The default initializers set the external name and also the default provider config ref. The bucket controller was explicitly using only the former.
I have:
=> Allow buckets to use a default providerConfigRef

apis/iam/v1alpha1/referencers.go, apis/kms/v1alpha1/referencers.go, apis/storage/v1alpha1/referencers.go
Signed-off-by: Hasan Turken <turkenh@gmail.com>
Reference to member field referenced via ServiceAccount object gets resolved before ServiceAccount being created and properly reporting `status.atProvider.email`. This PR fixes this by preventing reference being resolved beforehand.
I have:
Via a composition including a service account and a policy resource referencing to that service account. This way, we ended up both CRs being created together and observed the issue being fixed with this PR. Verified the fix prevents incomplete reference resolution.
=> Fix incomplete reference resolution of service account member

cmd/provider/main.go, go.mod, go.sum, pkg/controller/cache/managed.go, pkg/controller/compute/globaladdress.go, pkg/controller/compute/network.go, pkg/controller/compute/subnetwork.go, pkg/controller/config/config.go, pkg/controller/container/cluster.go, pkg/controller/container/nodepool.go, pkg/controller/database/cloudsql.go, pkg/controller/gcp.go, pkg/controller/iam/serviceaccount.go, pkg/controller/iam/serviceaccountpolicy.go, pkg/controller/kms/cryptokey.go, pkg/controller/kms/cryptokeypolicy.go, pkg/controller/kms/keyring.go, pkg/controller/pubsub/topic.go, pkg/controller/servicenetworking/connection.go, pkg/controller/storage/bucket.go, pkg/controller/storage/bucketpolicy.go, pkg/controller/storage/bucketpolicymember.go
Updates all controllers to use updated managed reconciler and a max of
rate limiter that accepts the provider-level token bucket limiter and a
per-item exponential backoff limiter with base delay of 1s and max delay
of 60s.
Same as https://github.com/crossplane/provider-aws/pull/544
I have:
=> Update all controllers to use default managed rate limiter

cluster/local/integration_tests.sh
Equivalent of https://github.com/crossplane/provider-aws/pull/711
I have:
GH Action
=> e2e: update integration test script

cmd/provider/main.go, pkg/controller/cache/managed.go, pkg/controller/compute/globaladdress.go, pkg/controller/compute/network.go, pkg/controller/compute/subnetwork.go, pkg/controller/container/cluster.go, pkg/controller/container/nodepool.go, pkg/controller/database/cloudsql.go, pkg/controller/gcp.go, pkg/controller/iam/serviceaccount.go, pkg/controller/iam/serviceaccountkey.go, pkg/controller/iam/serviceaccountpolicy.go, pkg/controller/kms/cryptokey.go, pkg/controller/kms/cryptokeypolicy.go, pkg/controller/kms/keyring.go, pkg/controller/pubsub/topic.go, pkg/controller/servicenetworking/connection.go, pkg/controller/storage/bucket.go, pkg/controller/storage/bucketpolicy.go, pkg/controller/storage/bucketpolicymember.go
Adds a `--poll-interval` flag to provider, which is passed to all controllers to set their polling interval in the reconciliation happy path.
*Note to reviewers: these changes are almost entirely find and replace.*
xref https://github.com/crossplane/crossplane-runtime/issues/253
I have:
See https://github.com/crossplane/provider-aws/pull/741 for testing steps.
=> Add global poll interval flag

Makefile
Simple change fixing provider binary name for make run.
This PR also bumps build submodule to latest.
Fixes #346 
I have:
`make run`
=> Fix make run by using correct binary name and use latest build module

examples/compute/network.yaml, examples/compute/subnetwork.yaml
as it is throwing validation errors:
```
error: error validating "crossplane-config/gcp/nework.yaml": error
validating data: ValidationError(Network.spec): unknown field
"reclaimPolicy" in io.crossplane.gcp.compute.v1beta1.Network.spec;
network.compute.gcp.crossplane.io/ng-network created
error: error validating "crossplane-config/gcp/nework.yaml": error
validating data: ValidationError(Subnetwork.spec): unknown field
"reclaimPolicy" in
io.crossplane.gcp.compute.v1beta1.Subnetwork.spec;
```
=> Remove reclaimPolicy line form both Network and Subnetwork

pkg/clients/nodepool/nodepool.go
Nodepool resource could be created with both lower and upper case `spec.forProvider.config.imageType` but gcloud always returns upper case version which is considered as a configuration difference causing continuous upgrades.
This PR aims to fix this by always using the upper case version while generating the desired spec.
Fixes #361
I have:
Using the manifests in #361, make sure that the casing in the image type field does not trigger an update.
=> Always convert nodepool image type to upper case

apis/iam/v1alpha1/referencers.go, pkg/clients/gcp.go, pkg/controller/iam/serviceaccountkey.go, pkg/controller/iam/serviceaccountkey_test.go
It appears that deleting a service account makes the service account key Get call return HTTP 403 Forbidden for some period of time. In this situation the service account (and thus all keys) are in practice gone.
Unfortunately we can't really distinguish between the key being gone and an actual permission error, but presumably if we treat a 403 during Observe as the key not existing we'd get another 403 when we tried to create it (in cases where the ServiceAccountKey managed resource is not being deleted).
```
Events:
Type     Reason                         Age              From                                             Message
----     ------                         ----             ----                                             -------
Normal   CreatedExternalResource        62s …
```
=> Consider HTTP 403 to mean a `ServiceAccountKey` does not exist

apis/database/v1beta1/cloudsql_instance_types.go, package/crds/database.gcp.crossplane.io_cloudsqlinstances.yaml
Google Cloud API expects the resource link for the VPC network for [the CloudSQL private network field](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#IpConfiguration). However, it also accepts VPC name (e.g. "default") but looks like it internally converts it to resource link by assuming it is in the same project, (projects/[project]/global/networks/[name]). This is causing issues like #352 where users are not aware about the underlying problem.
This PR adds a pattern validation on CRD using kubebuilder marker (thanks @hasheddan for pointing that out). 
Fixes #352 
I have:
1. Create a cloudsql instance in the expected format and verify it is created properly (and not getting periodic updates)
2. Create the following resource and verify that a proper error is …
=> Validate private network for cloudsql is in expected format

apis/database/v1beta1/cloudsql_instance_types.go, examples/database/cloudsql.yaml, package/crds/database.gcp.crossplane.io_cloudsqlinstances.yaml, pkg/clients/cloudsql/cloudsql.go, pkg/clients/cloudsql/cloudsql_test.go
Fixes #371
I have:
1. Create db with 20Gb and autoresize enabled
2. Increase size to 30Gb from console
3. Verify resource CR updates spec with this value
4. Increase value from resource CR, verify it is reflected
5. Try to decrease, verify not possible.
Also see unit tests.
=> Handle storage autoresize in cloudsql

docs/upgrading-to-v0.18.x.md, pkg/clients/cluster/cluster.go
Adds a guide for handling breaking API changes while upgrading to `v0.18.x`.
This PR also fixes an issue with late initializing during importing a resource which causes a nil pointer exception. 
I have:
1. Install [platorm-ref-gcp configuration] using package `registry.upbound.io/upbound/platform-ref-gcp:v0.0.5`
2. Create example network and cluster resources there.
3. Follow migration guide and upgrade to provider-gcp latest master (`v0.18.0-2.g0206b41`)
4. Upgrade configuration package to `registry.upbound.io/hasan/test-platform-ref-gcp:v0.0.6` which is built from [this PR](https://github.com/upbound/platform-ref-gcp/pull/15)
[platorm-ref-gcp configuration]: https://github.com/upbound/platform-ref-gcp
=> Add guide for upgrading to v0.18.x

apis/database/v1beta1/cloudsql_instance_types.go, package/crds/database.gcp.crossplane.io_cloudsqlinstances.yaml
This change updates the list of available postgres versions to match Google documentation, adding 10, 12 and 13. Without this change only 9_6 and 11 are listed for postgres.
I have:
The available versions were validated by leveraging the provider through Crossplane.
=> Update available postgres versions

examples/iam/serviceaccount/serviceaccountpolicy.yaml
`vault-system/vault` is not used anywhere in this repo so better to use the format mentioned in the reference.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> Better member name format for roles/iam.workloadIdentityUser

cmd/provider/main.go, go.mod, go.sum, pkg/controller/cache/managed.go, pkg/controller/compute/firewall.go, pkg/controller/compute/globaladdress.go, pkg/controller/compute/network.go, pkg/controller/compute/router.go, pkg/controller/compute/subnetwork.go, pkg/controller/config/config.go, pkg/controller/container/cluster.go, pkg/controller/container/nodepool.go, pkg/controller/database/cloudsql.go, pkg/controller/dns/resource_record_set.go, pkg/controller/gcp.go, pkg/controller/iam/serviceaccount.go, pkg/controller/iam/serviceaccountkey.go, pkg/controller/iam/serviceaccountpolicy.go, pkg/controller/kms/cryptokey.go, pkg/controller/kms/cryptokeypolicy.go, pkg/controller/kms/keyring.go, pkg/controller/pubsub/subscription.go, pkg/controller/pubsub/topic.go, pkg/controller/servicenetworking/connection.go, pkg/controller/storage/bucket.go, pkg/controller/storage/bucketpolicy.go, pkg/controller/storage/bucketpolicymember.go
Partially addresses crossplane/crossplane#2595 - see that issue for details.
I have:
I tested this together with https://github.com/crossplane/crossplane/pull/2602. See https://github.com/crossplane/crossplane/issues/2568#issuecomment-947086983 for details.
=> Support configurable reconcile rates

apis/v1beta1/providerconfig_types.go, docs/AUTHENTICATION.md, go.mod, go.sum, package/crds/gcp.crossplane.io_providerconfigs.yaml, pkg/clients/gcp.go
Adds support for Workload Identity, with which credentials no longer need to be present in Secrets.
If `InjectedIdentity` is specified, a token source for application default credentials by a GCP Service Account, which is specified in the `iam.gke.io/gcp-service-account` annotation of a provider's Kubernetes Service Account, is used for authentication.
Signed-off-by: micnncim <micnncim@gmail.com>
Fixes #173
I have:
Tested this in the following environment and process.
```console
$ kubectl version --short
Client Version: v1.20.7
Server Version: v1.20.12-gke.1500
```
```console
$ gcloud container clusters describe $CLUSTER --format="value(workloadIdentityConfig.workloadPool)"
$PROJECT_ID.svc.id.goog
```
```console
$ kubectl get deploy crossplane …
```
=> Support Workload Identity

docs/AUTHENTICATION.md
This removes a comment from the AUTHENTICATION for workloadIdentity, which causes confusion and results in a non-working example.
As the values are critical to the walkthrough, and we create the `controllerConfig` resource later in the guide, this makes no sense.
This is a documentation change, noticed while deploying `crossplane-gcp` to a new cluster/environment.
=> Removal of comment for controllerConfigRef

cluster/local/integration_tests.sh, examples/gke/gke.yaml
Fixes #413
I have:
Creating a `Cluster` and `NodePool` managed resources and checking that the ServiceAccount used by the `NodePool` was the one that was specified in the manifest
=> Fix GKE ServiceAccount field in examples

.github/workflows/ci.yml, apis/v1alpha1/doc.go, apis/v1alpha1/register.go, examples/storeconfig/kubernetes.yaml, examples/storeconfig/vault.yaml, package/crds/gcp.crossplane.io_storeconfigs.yaml
This PR changes the group name for `StoreConfig` from `gcp.secrets.crossplane.io` to `gcp.crossplane.io` to be consistent with  `ProviderConfig`.
I have:
By following [the updated guide](https://github.com/crossplane/crossplane/pull/3021).
=> Use consistent group name for StoreConfig as ProviderConfig

pkg/clients/cluster/cluster.go, pkg/clients/cluster/cluster_test.go
Fixes #385 
Provide LOAD_BALANCER_TYPE_UNSPECIFIED as default if nothing is specified, seems to be necessary.
I have:
1. make build -j4
2. make dev/run
=> Fixes #385

apis/container/v1beta2/cluster_types.go, package/crds/container.gcp.crossplane.io_clusters.yaml
=> fixing broken links about GCP documentation

apis/storage/v1alpha3/types.go, package/crds/storage.gcp.crossplane.io_buckets.yaml
Fixes a typo in the Bucket resource json attribute for the `PredefinedDefaultObjectAcl` field.
I have:
`make generate` runs and the openapi schema is updated to reflect the fixed typo. All unit tests pass.
=> Update typo in Bucket resource: predefinedCefaultObjectAcl to predefinedDefaultObjectAcl

apis/pubsub/v1alpha1/topic_types.go, apis/pubsub/v1alpha1/zz_generated.deepcopy.go, package/crds/pubsub.gcp.crossplane.io_topics.yaml, pkg/clients/topic/topic.go, pkg/clients/topic/topic_test.go
Fixes #422
I have:
- Managing the `messageRetentionDuration` field using the managed resource
- Adding tests
Currently, it is possible to use a fractional number in the `messageRetentionDuration` field, for example: 1200.5s.
This will cause an update-loop in the managed resource, because the API returns the value as `1200.500s`, which is "different" in our comparisons.
This bug won't appear if the platform builder uses an integer, for example, `1200s`. In this case, the GCP API will return `1200s` and it will be considered up to date.
I decided to not include this parser to include zeros/exclude zeros after the dot before the comparisons for simplicity for now,  but if you think it is crucial for this feature, please request changes :)
=> Add messageRetentionDuration to PubSub Topic

README.md
In the Readme, the URL returning the documentation was bad. I propose **https://crossplane.io/docs/**
I have:
**How has this code been tested**
Not necessary.
=> Readme: fix bad URL (404 error)

cmd/provider/main.go, docs/AUTHENTICATION.md, pkg/clients/gcp.go
Signed-off-by: Brad Wadsworth <brad.wadsworth@mavenwave.com>
This change will read the secret key in a Kubernetes secret and if it is not in a JSON format, it will treat it as a Access Token. The documentation has also been updated to demonstrate how a CronJob resource can keep the Access Token up to date 
Fixes #460 
I have:
Tested the change in a Kind cluster using the update `docs/AUTHENTICATION.md`.
=> Added Ability to use Access Tokens

OWNERS.md
Adding myself as a maintainer as my team is using this provider and we want to make sure it is maintained for as long as we continue to do so.   Doing this in light of the recent announcement that Upbound dev's will no longer contribute to the community providers.
This search 
https://github.com/search?q=+commenter%3Adee0++commenter%3Adee0sap+org%3Acrossplane+org%3Akubernetes+org%3Akubernetes-sigs+org%3Acrossplane-contrib+&type=issues
shows my contributions to the community within github as of 2023-08-29.    I suppose the most significant contributions in github are the PR and the assistance in resolving provider-aws issue [802](https://github.com/crossplane-contrib/provider-aws/issues/802).
This is me on linkedin
https://www.linkedin.com/in/dansmallproblemsolver/
.  Have been with SAP …
=> Add myself as maintainer
